import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vercel Avatar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Avatar</h1>

        <div style={{ display: 'flex', gap: 10 }}>
          <img
            className={styles.avatar}
            src="/avatar/vercel.svg?text=GR"
            alt="Vercel"
          />
          <img className={styles.avatar} src="/avatar/1" alt="Vercel" />
          <img className={styles.avatar} src="/avatar/satori" alt="Vercel" />
          <img className={styles.avatar} src="/avatar/nextjs" alt="Vercel" />
          <img className={styles.avatar} src="/avatar/nuxtjs" alt="Vercel" />
          <img className={styles.avatar} src="/qr/hello" alt="Vercel" />
        </div>
      </main>


    </div>
  );
}
